# Generated by Django 4.2.25 on 2025-10-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Um nome para identificar o ambiente.', max_length=100)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EXECUTANDO', 'Em Execução'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('limite_cpu', models.IntegerField(default=10, help_text='Percentual máximo de CPU a ser alocado (ex: 10 para 10%).')),
                ('limite_memoria', models.IntegerField(default=256, help_text='Memória máxima em MB a ser alocada (ex: 256).')),
                ('comando', models.TextField(help_text='O programa, comando ou script a ser executado.')),
                ('arquivo_saida', models.CharField(blank=True, help_text='Caminho do arquivo para onde a saída será redirecionada.', max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
